"use client";
/* eslint-disable @next/next/no-img-element -- authenticated private Blob streams are intentionally rendered directly */
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { FileImage, FileText, Trash2, UploadCloud } from "lucide-react";
import { clientApi } from "@/lib/client-api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
type Document = { id: string; originalFilename: string; mimeType: string; sizeBytes: number; createdAt: string; linkCount: number };
export function InboxManager() {
  const [items, setItems] = useState<Document[]>([]); const [files, setFiles] = useState<FileList | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => clientApi<Document[]>("/api/documents?limit=100").then(setItems).catch((e) => setError(e.message)); useEffect(() => { load(); const refresh = () => load(); window.addEventListener("documake:data-changed", refresh); return () => window.removeEventListener("documake:data-changed", refresh); }, []);
  async function upload(event: FormEvent) { event.preventDefault(); if (!files?.length) return; setBusy(true); setError(""); const form = new FormData(); Array.from(files).forEach((file) => form.append("files", file)); try { await clientApi("/api/documents", { method: "POST", body: form }); setFiles(null); const input = document.getElementById("document-files") as HTMLInputElement | null; if (input) input.value = ""; await load(); } catch (e) { setError(e instanceof Error ? e.message : "Upload failed."); } finally { setBusy(false); } }
  async function remove(item: Document) { if (!confirm(`Delete “${item.originalFilename}”? This permanently removes the private Blob and all record links.`)) return; try { await clientApi(`/api/documents/${item.id}`, { method: "DELETE" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Delete failed."); } }
  return <div className="mt-8 space-y-6">{error && <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Card className="paper-grid overflow-hidden border-dashed border-ink/20 p-7 sm:p-10"><form onSubmit={upload} className="flex flex-col items-center text-center"><span className="grid size-12 place-items-center rounded-2xl bg-ink text-white shadow-lg shadow-ink/15"><UploadCloud className="size-5" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[0.13em] text-coral-strong">Bring in the source</p><h2 className="mt-1 text-xl font-bold text-ink">Upload images or PDFs</h2><p className="mt-2 max-w-lg text-sm leading-6 text-muted">Choose up to 10 files, 10 MB each. Your originals stay private and ready to connect to any record.</p><input id="document-files" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(e) => setFiles(e.target.files)} className="mt-5 block max-w-full text-sm text-muted file:mr-3 file:rounded-xl file:border-0 file:bg-white file:px-4 file:py-2.5 file:text-sm file:font-semibold file:text-ink file:shadow-sm" /><Button disabled={busy || !files?.length} className="mt-4">{busy ? "Uploading…" : `Upload${files?.length ? ` ${files.length} file${files.length > 1 ? "s" : ""}` : ""}`}</Button></form></Card>
      {items.length ? <div className="stagger-children grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map((item) => <Card key={item.id} className="hover-lift group overflow-hidden"><Link href={`/documents/${item.id}`} className="block"><div className="relative grid aspect-[4/3] place-items-center overflow-hidden bg-paper">{item.mimeType.startsWith("image/") ? <img src={`/api/documents/${item.id}/content`} alt="" className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.035]" /> : <FileText className="size-12 text-ink/25" />}<span className="absolute left-3 top-3 rounded-full bg-ink/85 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-white backdrop-blur">{item.mimeType === "application/pdf" ? "PDF" : "Image"}</span></div><div className="p-4"><p className="truncate text-sm font-bold text-ink">{item.originalFilename}</p><p className="mt-1 text-xs text-muted">{(item.sizeBytes / 1024 / 1024).toFixed(1)} MB · {Number(item.linkCount) ? `linked to ${item.linkCount} record${Number(item.linkCount) === 1 ? "" : "s"}` : "ready to link"}</p></div></Link><button onClick={() => remove(item)} className="absolute sr-only"><Trash2 />Delete</button><div className="border-t px-4 py-2 text-right"><button onClick={() => remove(item)} className="inline-flex items-center gap-1 text-xs font-semibold text-muted hover:text-red-600"><Trash2 className="size-3.5" />Delete</button></div></Card>)}</div> : <Card className="grid min-h-64 place-items-center p-8 text-center"><div><FileImage className="mx-auto size-8 text-muted/50" /><p className="mt-3 text-sm font-semibold text-ink">Your source shelf is empty</p><p className="mt-1 text-sm text-muted">Add the first image or PDF whenever you are ready.</p></div></Card>}
  </div>;
}
